const std = @import("std");

pub const InputCode = enum(u16) {
    // Mouse buttons (interpreted by mouse device)
    mouse_left = 1000,
    mouse_right = 1001,
    mouse_middle = 1002,
    mouse_button4 = 1003,
    mouse_button5 = 1004,
    mouse_button6 = 1005,
    mouse_button7 = 1006,
    mouse_button8 = 1007,
    mouse_button9 = 1008,
    mouse_button10 = 1009,
    mouse_button11 = 1010,
    mouse_button12 = 1011,
    mouse_button13 = 1012,
    mouse_button14 = 1013,
    mouse_button15 = 1014,
    mouse_button16 = 1015,

    // Gamepad buttons (physical-position names, interpreted by gamepad device)
    gamepad_face_south = 2000,
    gamepad_face_east = 2001,
    gamepad_face_west = 2002,
    gamepad_face_north = 2003,
    gamepad_dpad_up = 2004,
    gamepad_dpad_down = 2005,
    gamepad_dpad_left = 2006,
    gamepad_dpad_right = 2007,
    gamepad_left_shoulder = 2008,
    gamepad_right_shoulder = 2009,
    gamepad_left_trigger = 2010,
    gamepad_right_trigger = 2011,
    gamepad_select = 2012,
    gamepad_start = 2013,
    gamepad_home = 2014,
    gamepad_left_stick_press = 2015,
    gamepad_right_stick_press = 2016,
    gamepad_capture = 2017,
    gamepad_left_stick = 2018,
    gamepad_right_stick = 2019,
    gamepad_left_stick_up = 2020,
    gamepad_left_stick_down = 2021,
    gamepad_left_stick_left = 2022,
    gamepad_left_stick_right = 2023,
    gamepad_right_stick_up = 2024,
    gamepad_right_stick_down = 2025,
    gamepad_right_stick_left = 2026,
    gamepad_right_stick_right = 2027,

    // Keyboard keys (layout-level, shift-agnostic)
    key_backspace = 8,
    key_tab = 9,
    key_enter = 13,
    key_pause = 19,
    key_caps_lock = 20,
    key_escape = 27,
    key_space = 32,
    key_page_up = 33,
    key_page_down = 34,
    key_end = 35,
    key_home = 36,
    key_left = 37,
    key_up = 38,
    key_right = 39,
    key_down = 40,
    key_print_screen = 44,
    key_insert = 45,
    key_delete = 46,

    key_0 = 48,
    key_1 = 49,
    key_2 = 50,
    key_3 = 51,
    key_4 = 52,
    key_5 = 53,
    key_6 = 54,
    key_7 = 55,
    key_8 = 56,
    key_9 = 57,

    key_a = 65,
    key_b = 66,
    key_c = 67,
    key_d = 68,
    key_e = 69,
    key_f = 70,
    key_g = 71,
    key_h = 72,
    key_i = 73,
    key_j = 74,
    key_k = 75,
    key_l = 76,
    key_m = 77,
    key_n = 78,
    key_o = 79,
    key_p = 80,
    key_q = 81,
    key_r = 82,
    key_s = 83,
    key_t = 84,
    key_u = 85,
    key_v = 86,
    key_w = 87,
    key_x = 88,
    key_y = 89,
    key_z = 90,

    key_super_left = 91,
    key_super_right = 92,
    key_menu = 93,

    key_numpad_0 = 96,
    key_numpad_1 = 97,
    key_numpad_2 = 98,
    key_numpad_3 = 99,
    key_numpad_4 = 100,
    key_numpad_5 = 101,
    key_numpad_6 = 102,
    key_numpad_7 = 103,
    key_numpad_8 = 104,
    key_numpad_9 = 105,
    key_numpad_multiply = 106,
    key_numpad_add = 107,
    key_numpad_subtract = 109,
    key_numpad_decimal = 110,
    key_numpad_divide = 111,

    key_f1 = 112,
    key_f2 = 113,
    key_f3 = 114,
    key_f4 = 115,
    key_f5 = 116,
    key_f6 = 117,
    key_f7 = 118,
    key_f8 = 119,
    key_f9 = 120,
    key_f10 = 121,
    key_f11 = 122,
    key_f12 = 123,
    key_f13 = 124,
    key_f14 = 125,
    key_f15 = 126,
    key_f16 = 127,
    key_f17 = 128,
    key_f18 = 129,
    key_f19 = 130,
    key_f20 = 131,
    key_f21 = 132,
    key_f22 = 133,
    key_f23 = 134,
    key_f24 = 135,

    key_num_lock = 144,
    key_scroll_lock = 145,

    key_shift_left = 160,
    key_shift_right = 161,
    key_control_left = 162,
    key_control_right = 163,
    key_alt_left = 164,
    key_alt_right = 165,

    // Keep enum open for additional backend-specific values.
    _,
};

pub fn inputCodeName(code: InputCode) ?[]const u8 {
    inline for (std.meta.fields(InputCode)) |field| {
        if (@intFromEnum(code) == field.value) return field.name;
    }
    return null;
}

pub fn parseInputCode(name: []const u8) ?InputCode {
    inline for (std.meta.fields(InputCode)) |field| {
        if (std.mem.eql(u8, name, field.name)) {
            return @as(InputCode, @enumFromInt(field.value));
        }
    }
    return null;
}

pub fn inputCodeLabel(code: InputCode) ?[]const u8 {
    return switch (code) {
        .mouse_left => "Mouse Left",
        .mouse_right => "Mouse Right",
        .mouse_middle => "Mouse Middle",
        .mouse_button4 => "Mouse Button 4",
        .mouse_button5 => "Mouse Button 5",
        .mouse_button6 => "Mouse Button 6",
        .mouse_button7 => "Mouse Button 7",
        .mouse_button8 => "Mouse Button 8",
        .mouse_button9 => "Mouse Button 9",
        .mouse_button10 => "Mouse Button 10",
        .mouse_button11 => "Mouse Button 11",
        .mouse_button12 => "Mouse Button 12",
        .mouse_button13 => "Mouse Button 13",
        .mouse_button14 => "Mouse Button 14",
        .mouse_button15 => "Mouse Button 15",
        .mouse_button16 => "Mouse Button 16",
        .gamepad_face_south => "Gamepad Face South",
        .gamepad_face_east => "Gamepad Face East",
        .gamepad_face_west => "Gamepad Face West",
        .gamepad_face_north => "Gamepad Face North",
        .gamepad_dpad_up => "Gamepad D-pad Up",
        .gamepad_dpad_down => "Gamepad D-pad Down",
        .gamepad_dpad_left => "Gamepad D-pad Left",
        .gamepad_dpad_right => "Gamepad D-pad Right",
        .gamepad_left_shoulder => "Gamepad Left Shoulder",
        .gamepad_right_shoulder => "Gamepad Right Shoulder",
        .gamepad_left_trigger => "Gamepad Left Trigger",
        .gamepad_right_trigger => "Gamepad Right Trigger",
        .gamepad_select => "Gamepad Select",
        .gamepad_start => "Gamepad Start",
        .gamepad_home => "Gamepad Home",
        .gamepad_left_stick_press => "Gamepad Left Stick Press",
        .gamepad_right_stick_press => "Gamepad Right Stick Press",
        .gamepad_capture => "Gamepad Capture",
        .gamepad_left_stick => "Gamepad Left Stick",
        .gamepad_right_stick => "Gamepad Right Stick",
        .gamepad_left_stick_up => "Gamepad Left Stick Up",
        .gamepad_left_stick_down => "Gamepad Left Stick Down",
        .gamepad_left_stick_left => "Gamepad Left Stick Left",
        .gamepad_left_stick_right => "Gamepad Left Stick Right",
        .gamepad_right_stick_up => "Gamepad Right Stick Up",
        .gamepad_right_stick_down => "Gamepad Right Stick Down",
        .gamepad_right_stick_left => "Gamepad Right Stick Left",
        .gamepad_right_stick_right => "Gamepad Right Stick Right",
        .key_backspace => "Backspace",
        .key_tab => "Tab",
        .key_enter => "Enter",
        .key_pause => "Pause",
        .key_caps_lock => "Caps Lock",
        .key_escape => "Escape",
        .key_space => "Space",
        .key_page_up => "Page Up",
        .key_page_down => "Page Down",
        .key_end => "End",
        .key_home => "Home",
        .key_left => "Left",
        .key_up => "Up",
        .key_right => "Right",
        .key_down => "Down",
        .key_print_screen => "Print Screen",
        .key_insert => "Insert",
        .key_delete => "Delete",
        .key_0 => "0",
        .key_1 => "1",
        .key_2 => "2",
        .key_3 => "3",
        .key_4 => "4",
        .key_5 => "5",
        .key_6 => "6",
        .key_7 => "7",
        .key_8 => "8",
        .key_9 => "9",
        .key_a => "A",
        .key_b => "B",
        .key_c => "C",
        .key_d => "D",
        .key_e => "E",
        .key_f => "F",
        .key_g => "G",
        .key_h => "H",
        .key_i => "I",
        .key_j => "J",
        .key_k => "K",
        .key_l => "L",
        .key_m => "M",
        .key_n => "N",
        .key_o => "O",
        .key_p => "P",
        .key_q => "Q",
        .key_r => "R",
        .key_s => "S",
        .key_t => "T",
        .key_u => "U",
        .key_v => "V",
        .key_w => "W",
        .key_x => "X",
        .key_y => "Y",
        .key_z => "Z",
        .key_super_left => "Left Super",
        .key_super_right => "Right Super",
        .key_menu => "Menu",
        .key_numpad_0 => "Numpad 0",
        .key_numpad_1 => "Numpad 1",
        .key_numpad_2 => "Numpad 2",
        .key_numpad_3 => "Numpad 3",
        .key_numpad_4 => "Numpad 4",
        .key_numpad_5 => "Numpad 5",
        .key_numpad_6 => "Numpad 6",
        .key_numpad_7 => "Numpad 7",
        .key_numpad_8 => "Numpad 8",
        .key_numpad_9 => "Numpad 9",
        .key_numpad_multiply => "Numpad Multiply",
        .key_numpad_add => "Numpad Add",
        .key_numpad_subtract => "Numpad Subtract",
        .key_numpad_decimal => "Numpad Decimal",
        .key_numpad_divide => "Numpad Divide",
        .key_f1 => "F1",
        .key_f2 => "F2",
        .key_f3 => "F3",
        .key_f4 => "F4",
        .key_f5 => "F5",
        .key_f6 => "F6",
        .key_f7 => "F7",
        .key_f8 => "F8",
        .key_f9 => "F9",
        .key_f10 => "F10",
        .key_f11 => "F11",
        .key_f12 => "F12",
        .key_f13 => "F13",
        .key_f14 => "F14",
        .key_f15 => "F15",
        .key_f16 => "F16",
        .key_f17 => "F17",
        .key_f18 => "F18",
        .key_f19 => "F19",
        .key_f20 => "F20",
        .key_f21 => "F21",
        .key_f22 => "F22",
        .key_f23 => "F23",
        .key_f24 => "F24",
        .key_num_lock => "Num Lock",
        .key_scroll_lock => "Scroll Lock",
        .key_shift_left => "Left Shift",
        .key_shift_right => "Right Shift",
        .key_control_left => "Left Control",
        .key_control_right => "Right Control",
        .key_alt_left => "Left Alt",
        .key_alt_right => "Right Alt",
        else => inputCodeName(code),
    };
}
