name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig (0.17-dev)
        uses: mlugg/setup-zig@v1
        with:
          version: master   # 最新的开发版，即 0.17.0-dev why

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev libxkbcommon-dev libx11-dev

      - name: Build project
        run: zig build debug-input